version: "3.1"

services:
  wordpress:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    restart: "no"
    ports:
      - ${WP_HTTP_PORT:-8000}:80
    depends_on:
      - cache
      - db
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: domain
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'cache');
        define( 'WP_REDIS_DATABASE', 0);
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_HOME', 'http://localhost:${WP_HTTP_PORT:-8000}' );
        define( 'WP_SITEURL', 'http://localhost:${WP_HTTP_PORT:-8000}' );
    volumes:
      - ./src:/var/www/html:delegated

  db:
    image: mysql:8
    container_name: ${COMPOSE_PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./transfer:/docker-entrypoint-initdb.d:delegated
      - db:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    restart: "no"

  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: "no"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - ${ADMINER_HTTP_PORT:-8001}:8080

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpredisadmin
    environment:
      - REDIS_1_HOST=cache
      - REDIS_1_PORT=6379
    depends_on:
      - cache
    ports:
      - ${REDIS_ADMIN_HTTP_PORT:-8002}:80

volumes:
  db:
