#!/usr/bin/env bash

MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=domain

DB_CONTAINER="$(docker ps -q -f NAME=db)"
echo $DB_CONTAINER
docker exec -ti ${DB_CONTAINER} bash -c 'mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" > /docker-entrypoint-initdb.d/dump.sql && gzip -f /docker-entrypoint-initdb.d/dump.sql'
